import { EnumOfColors, EnumOfCompanies, EnumOfTypes } from './../types/productTypes';
import { imagesBakes, foreignImagesBakes } from './imagesConst';
import { IProduct } from './../types/productTypes';

let b1: Array<IProduct> = [];

b1 = [
    //горные
    {
        uuid: '100',
        id: '99100',
        name: 'Welt Ridge',
        price: 21000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.mountain,
        img: imagesBakes[0],
        foreignImg: foreignImagesBakes[0],
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.orange, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[0],
            [EnumOfColors.orange]: imagesBakes[1],
            [EnumOfColors.black]: imagesBakes[2],
        },
        searchString: 'welt ridge stinger горный синий',
        description: 'Спортивный велосипед укомплектован дисковыми механическими тормозами, оборудованием фирмы Stinger и амортизационной вилкой. Dakota рекомендован для катания по паркам и пересеченной местности.'
    },
    {
        uuid: '100',
        id: '10100',
        name: 'Welt Ridge',
        price: 21000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.mountain,
        img: imagesBakes[1],
        foreignImg: foreignImagesBakes[1],
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.blue, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[0],
            [EnumOfColors.orange]: imagesBakes[1],
            [EnumOfColors.black]: imagesBakes[2],
        },
        searchString: 'welt ridge stinger горный оранжевый',
        description: 'Спортивный велосипед укомплектован дисковыми механическими тормозами, оборудованием фирмы Stinger и амортизационной вилкой. Dakota рекомендован для катания по паркам и пересеченной местности.'
    },
    {
        uuid: '100',
        id: '20100',
        name: 'Welt Ridge',
        price: 21000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.mountain,
        img: imagesBakes[2],
        foreignImg: foreignImagesBakes[2],
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.blue, EnumOfColors.orange],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[0],
            [EnumOfColors.orange]: imagesBakes[1],
            [EnumOfColors.black]: imagesBakes[2],
        },
        searchString: 'welt ridge stinger горный черный',
        description: 'Спортивный велосипед укомплектован дисковыми механическими тормозами, оборудованием фирмы Stinger и амортизационной вилкой. Dakota рекомендован для катания по паркам и пересеченной местности.'
    },

    {
        uuid: '101',
        id: '98101',
        name: 'Sporting',
        price: 27000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.mountain,
        img: imagesBakes[3],
        foreignImg: foreignImagesBakes[3],
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.grey]: imagesBakes[3],
            [EnumOfColors.green]: imagesBakes[4],
            [EnumOfColors.black]: imagesBakes[5],
        },
        searchString: 'sporting merida горный серый',
        description: 'Горный велосипед для катания в стиле кросс кантри с колесами диаметром 27.5 дюйма. Как и все модели этого ведущего немецкого бренда, рама выполнена из высокопрочного алюминиевого сплава 7005, что гарантирует не только долговечность, но и отличный накат.'
    },
    {
        uuid: '101',
        id: '40101',
        name: 'Sporting',
        price: 27000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.mountain,
        img: imagesBakes[4],
        foreignImg: foreignImagesBakes[4],
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.grey, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.green]: imagesBakes[4],
            [EnumOfColors.grey]: imagesBakes[3],
            [EnumOfColors.black]: imagesBakes[5],
        },
        searchString: 'sporting merida горный зелёный',
        description: 'Горный велосипед для катания в стиле кросс кантри с колесами диаметром 27.5 дюйма. Как и все модели этого ведущего немецкого бренда, рама выполнена из высокопрочного алюминиевого сплава 7005, что гарантирует не только долговечность, но и отличный накат.'
    },
    {
        uuid: '101',
        id: '50101',
        name: 'Sporting',
        price: 27000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.mountain,
        img: imagesBakes[5],
        foreignImg: foreignImagesBakes[5],
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.green, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.black]: imagesBakes[5],
            [EnumOfColors.grey]: imagesBakes[3],
            [EnumOfColors.green]: imagesBakes[4],
        },
        searchString: 'sporting merida горный чёрный',
        description: 'Горный велосипед для катания в стиле кросс кантри с колесами диаметром 27.5 дюйма. Как и все модели этого ведущего немецкого бренда, рама выполнена из высокопрочного алюминиевого сплава 7005, что гарантирует не только долговечность, но и отличный накат.'
    },

    {
        uuid: '102',
        id: '11102',
        name: 'Marlin',
        img: imagesBakes[6],
        foreignImg: foreignImagesBakes[6],
        price: 31900,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[6],
            [EnumOfColors.grey]: imagesBakes[7],
            [EnumOfColors.red]: imagesBakes[8],
            [EnumOfColors.green]: imagesBakes[9],
        },
        searchString: 'marlin trek горный синий',
        description: 'Горный велосипед начального класса. Marlin изготовлен на алюминиевой раме и оснащен колесами 27.5 дюймов с универсальными покрышками. Модель рекомендована для катания по городу и пересеченной местности. Благодаря продуманной геометрии рамы велосипед хорошо управляется и устойчив на поворотах.',
    },
    {
        uuid: '102',
        id: '21102',
        name: 'Marlin',
        img: imagesBakes[7],
        foreignImg: foreignImagesBakes[7],
        price: 31900,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.red, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[6],
            [EnumOfColors.grey]: imagesBakes[7],
            [EnumOfColors.red]: imagesBakes[8],
            [EnumOfColors.green]: imagesBakes[9],
        },
        searchString: 'marlin trek горный серый',
        description: 'Горный велосипед начального класса. Marlin изготовлен на алюминиевой раме и оснащен колесами 27.5 дюймов с универсальными покрышками. Модель рекомендована для катания по городу и пересеченной местности. Благодаря продуманной геометрии рамы велосипед хорошо управляется и устойчив на поворотах.',
    },
    {
        uuid: '102',
        id: '31102',
        name: 'Marlin',
        img: imagesBakes[8],
        foreignImg: foreignImagesBakes[8],
        price: 31900,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.grey, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[6],
            [EnumOfColors.grey]: imagesBakes[7],
            [EnumOfColors.red]: imagesBakes[8],
            [EnumOfColors.green]: imagesBakes[9],
        },
        searchString: 'marlin trek горный красный',
        description: 'Горный велосипед начального класса. Marlin изготовлен на алюминиевой раме и оснащен колесами 27.5 дюймов с универсальными покрышками. Модель рекомендована для катания по городу и пересеченной местности. Благодаря продуманной геометрии рамы велосипед хорошо управляется и устойчив на поворотах.',
    },
    {
        uuid: '102',
        id: '97102',
        name: 'Marlin',
        img: imagesBakes[9],
        foreignImg: foreignImagesBakes[9],
        price: 31900,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[6],
            [EnumOfColors.grey]: imagesBakes[7],
            [EnumOfColors.red]: imagesBakes[8],
            [EnumOfColors.green]: imagesBakes[9],
        },
        searchString: 'marlin trek горный зелёный',
        description: 'Горный велосипед начального класса. Marlin изготовлен на алюминиевой раме и оснащен колесами 27.5 дюймов с универсальными покрышками. Модель рекомендована для катания по городу и пересеченной местности. Благодаря продуманной геометрии рамы велосипед хорошо управляется и устойчив на поворотах.',
    },

    {
        uuid: '103',
        id: '41103',
        name: 'Apache Classic',
        img: imagesBakes[10],
        foreignImg: foreignImagesBakes[10],
        price: 35700,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[10],
            [EnumOfColors.red]: imagesBakes[11],
        },
        searchString: 'apache classic bulls горный синий',
        description: 'Стихия этого велосипеда бездорожье и городские дороги. Для комфортного передвижения по неровным дорогам поможет воздушно-масляная амортизационная вилка Rock Shock Reba, с многочисленными настройками под конкретно свой стиль катания. Профессиональная система переключения передач, обеспечит владельца надежной и бесперебойной работой.',
    },
    {
        uuid: '103',
        id: '96103',
        name: 'Apache Classic',
        img: imagesBakes[11],
        foreignImg: foreignImagesBakes[11],
        price: 35700,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.blue],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[10],
            [EnumOfColors.red]: imagesBakes[11],
        },
        searchString: 'apache classic bulls горный красный',
        description: 'Стихия этого велосипеда бездорожье и городские дороги. Для комфортного передвижения по неровным дорогам поможет воздушно-масляная амортизационная вилка Rock Shock Reba, с многочисленными настройками под конкретно свой стиль катания. Профессиональная система переключения передач, обеспечит владельца надежной и бесперебойной работой.',
    },

    {
        uuid: '104',
        id: '22104',
        name: 'Apache',
        img: imagesBakes[12],
        foreignImg: foreignImagesBakes[12],
        price: 42000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.grey, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[12],
            [EnumOfColors.grey]: imagesBakes[13],
            [EnumOfColors.black]: imagesBakes[14],
        },
        searchString: 'apache stinger горный оранжевый',
        description: 'Сбалансированный вариант для езды по ухабистой местности и занятием фитнесом. Облегченная алюминиевая рама со специальным занижением рамы, позволит в полной мере контролировать велосипед, что обеспечит дополнительную маневренность при объезде препятствий. Гидравлические дисковые тормоза остановят в экстренной ситуации при разных видах погодных условий, и срабатывают от легко прикосновения к ручке.',
    },
    {
        uuid: '104',
        id: '32104',
        name: 'Apache',
        img: imagesBakes[13],
        foreignImg: foreignImagesBakes[13],
        price: 42000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.orange, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.grey]: imagesBakes[13],
            [EnumOfColors.orange]: imagesBakes[12],
            [EnumOfColors.black]: imagesBakes[14],
        },
        searchString: 'apache stinger горный серый',
        description: 'Сбалансированный вариант для езды по ухабистой местности и занятием фитнесом. Облегченная алюминиевая рама со специальным занижением рамы, позволит в полной мере контролировать велосипед, что обеспечит дополнительную маневренность при объезде препятствий. Гидравлические дисковые тормоза остановят в экстренной ситуации при разных видах погодных условий, и срабатывают от легко прикосновения к ручке.',
    },
    {
        uuid: '104',
        id: '42104',
        name: 'Apache',
        img: imagesBakes[14],
        foreignImg: foreignImagesBakes[14],
        price: 42000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.orange, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.black]: imagesBakes[14],
            [EnumOfColors.orange]: imagesBakes[12],
            [EnumOfColors.grey]: imagesBakes[13],
        },
        searchString: 'apache stinger горный черный',
        description: 'Сбалансированный вариант для езды по ухабистой местности и занятием фитнесом. Облегченная алюминиевая рама со специальным занижением рамы, позволит в полной мере контролировать велосипед, что обеспечит дополнительную маневренность при объезде препятствий. Гидравлические дисковые тормоза остановят в экстренной ситуации при разных видах погодных условий, и срабатывают от легко прикосновения к ручке.',
    },

    {
        uuid: '105',
        id: '52105',
        name: 'Sporting Evo',
        img: imagesBakes[15],
        foreignImg: foreignImagesBakes[15],
        price: 51000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[15],
            [EnumOfColors.red]: imagesBakes[16],
        },
        searchString: 'sporting evo bulls горный синий',
        description: 'Горный велосипед подходящий для смешанного катания, города и пересечённой местности. Благодаря надёжной трансмиссии и амортизационной вилке грунт и бездорожье-это те условия, в которых вы будете чувствовать себя комфортно и получать удовольствие от катания. Подойдёт как для ежедневного катания, так и для долгих туристических походов. Велосипед собран на высокотехнологичной алюминиевой раме и в отличии от младшего брата в этой линейке оснащён дисковыми механическими тормозами и имеет больший ход амортизационной вилки. Яркая матовая окраска делает байк безопаснее и придаёт ему индивидуальность.',
    },
    {
        uuid: '105',
        id: '94105',
        name: 'Sporting Evo',
        img: imagesBakes[16],
        foreignImg: foreignImagesBakes[16],
        price: 51000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.mountain,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.blue],
        imgsByColor: {
            [EnumOfColors.red]: imagesBakes[16],
            [EnumOfColors.blue]: imagesBakes[15],
        },
        searchString: 'sporting evo bulls горный красный',
        description: 'Горный велосипед подходящий для смешанного катания, города и пересечённой местности. Благодаря надёжной трансмиссии и амортизационной вилке грунт и бездорожье-это те условия, в которых вы будете чувствовать себя комфортно и получать удовольствие от катания. Подойдёт как для ежедневного катания, так и для долгих туристических походов. Велосипед собран на высокотехнологичной алюминиевой раме и в отличии от младшего брата в этой линейке оснащён дисковыми механическими тормозами и имеет больший ход амортизационной вилки. Яркая матовая окраска делает байк безопаснее и придаёт ему индивидуальность.',
    },

    // Двухподвесные 
    {
        uuid: '106',
        id: '93106',
        name: 'Versus',
        img: imagesBakes[17],
        foreignImg: foreignImagesBakes[17],
        price: 55000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.blue],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[17],
            [EnumOfColors.blue]: imagesBakes[18],
        },
        searchString: 'versus stinger двухподвесной оранжевый',
        description: 'Двухподвесный найнер с высоким уровнем комплектации, собранный на алюминиевой раме из облегчённого сплава, оснащённый двумя амортизаторами. Модель является по настоящему добротным и надёжным универсалом для катания по любому типу дорожного покрытия, это бездорожье или лесные тропинки с просеками.',
    },
    {
        uuid: '106',
        id: '13106',
        name: 'Versus',
        img: imagesBakes[18],
        foreignImg: foreignImagesBakes[18],
        price: 55000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.orange],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[17],
            [EnumOfColors.blue]: imagesBakes[18],
        },
        searchString: 'versus stinger двухподвесной синий',
        description: 'Двухподвесный найнер с высоким уровнем комплектации, собранный на алюминиевой раме из облегчённого сплава, оснащённый двумя амортизаторами. Модель является по настоящему добротным и надёжным универсалом для катания по любому типу дорожного покрытия, это бездорожье или лесные тропинки с просеками.',
    },

    {
        uuid: '107',
        id: '23107',
        name: 'Scott Genius',
        img: imagesBakes[19],
        foreignImg: foreignImagesBakes[19],
        price: 64000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.green, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[19],
            [EnumOfColors.green]: imagesBakes[20],
            [EnumOfColors.grey]: imagesBakes[21],
        },
        searchString: 'scott genius merida двухподвесной оранжевый',
        description: 'Двухподвесной велосипед для скоростного спуска и езды по бездорожью. Диаметр колёс-29 дюймов. Материал рамы- Карбон. Подойдет для фитнес нагрузок и участия в спортивных соревнованиях. Покрышки подходят для передвижения по всем типам грунта и неукатанному снегу.',
    },
    {
        uuid: '107',
        id: '92107',
        name: 'Scott Genius',
        img: imagesBakes[20],
        foreignImg: foreignImagesBakes[20],
        price: 64000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.orange, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[19],
            [EnumOfColors.green]: imagesBakes[20],
            [EnumOfColors.grey]: imagesBakes[21],
        },
        searchString: 'scott genius merida двухподвесной зелёный',
        description: 'Двухподвесной велосипед для скоростного спуска и езды по бездорожью. Диаметр колёс-29 дюймов. Материал рамы- Карбон. Подойдет для фитнес нагрузок и участия в спортивных соревнованиях. Покрышки подходят для передвижения по всем типам грунта и неукатанному снегу.',
    },
    {
        uuid: '107',
        id: '33107',
        name: 'Scott Genius',
        img: imagesBakes[21],
        foreignImg: foreignImagesBakes[21],
        price: 64000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.orange, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[19],
            [EnumOfColors.green]: imagesBakes[20],
            [EnumOfColors.grey]: imagesBakes[21],
        },
        searchString: 'scott genius merida двухподвесной серый',
        description: 'Двухподвесной велосипед для скоростного спуска и езды по бездорожью. Диаметр колёс-29 дюймов. Материал рамы- Карбон. Подойдет для фитнес нагрузок и участия в спортивных соревнованиях. Покрышки подходят для передвижения по всем типам грунта и неукатанному снегу.',
    },

    {
        uuid: '108',
        id: '43108',
        name: 'Scott Contessa',
        img: imagesBakes[22],
        foreignImg: foreignImagesBakes[22],
        price: 76000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[22],
            [EnumOfColors.red]: imagesBakes[23],
        },
        searchString: 'scott contessa trek двухподвесной синий',
        description: 'Двухподвесный найнер с высоким уровнем комплектации, собранный на алюминиевой раме из облегчённого сплава, оснащённый двумя амортизаторами. Модель является по настоящему добротным и надёжным универсалом для катания по любому типу дорожного покрытия, это бездорожье или лесные тропинки с просеками.',
    },
    {
        uuid: '108',
        id: '91108',
        name: 'Scott Contessa',
        img: imagesBakes[23],
        foreignImg: foreignImagesBakes[23],
        price: 76000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.blue],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[22],
            [EnumOfColors.red]: imagesBakes[23],
        },
        searchString: 'scott contessa trek двухподвесной красный',
        description: 'Двухподвесный найнер с высоким уровнем комплектации, собранный на алюминиевой раме из облегчённого сплава, оснащённый двумя амортизаторами. Модель является по настоящему добротным и надёжным универсалом для катания по любому типу дорожного покрытия, это бездорожье или лесные тропинки с просеками.',
    },

    {
        uuid: '109',
        id: '53109',
        name: 'Giant Trance',
        img: imagesBakes[24],
        foreignImg: foreignImagesBakes[24],
        price: 93000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.grey]: imagesBakes[24],
            [EnumOfColors.red]: imagesBakes[25],
        },
        searchString: 'giant trance bulls двухподвесной серый',
        description: 'Профессиональный горный велосипед собран на алюминиевой раме из лёгкого сплава с колесами 27.5 дюймов. Merida One Forty укомплектован оборудованием Sram и дисковыми гидравлическими тормозами. Велосипед рекомендован для езды как по городу так и по пересеченной местности.',
    },
    {
        uuid: '109',
        id: '14109',
        name: 'Giant Trance',
        img: imagesBakes[25],
        foreignImg: foreignImagesBakes[25],
        price: 93000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.grey]: imagesBakes[24],
            [EnumOfColors.red]: imagesBakes[25],
        },
        searchString: 'giant trance двухподвесной bulls красный',
        description: 'Профессиональный горный велосипед собран на алюминиевой раме из лёгкого сплава с колесами 27.5 дюймов. Merida One Forty укомплектован оборудованием Sram и дисковыми гидравлическими тормозами. Велосипед рекомендован для езды как по городу так и по пересеченной местности.',
    },

    {
        uuid: '110',
        id: '24110',
        name: 'Eone Sixty',
        img: imagesBakes[26],
        foreignImg: foreignImagesBakes[26],
        price: 98000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.green]: imagesBakes[26],
            [EnumOfColors.black]: imagesBakes[27],
        },
        searchString: 'eone sixty merida двухподвесной зелёный',
        description: 'Велосипед, созданный для жесткой эксплуатации в горах. Руль шириной 800 мм станет идеальным инструментом контроля на спусках. Производитель позаботился о сохранности рамы, оснастил заднее перо заводской защитой от ударов цепи, которая органично смотрится и не выглядит чужеродным элементом. Подвеска Maestro гасит удары и рассчитана на повышенные нагрузки, в том числе благодаря пружинному амортизатору.',
    },
    {
        uuid: '110',
        id: '89110',
        name: 'Eone Sixty',
        img: imagesBakes[27],
        foreignImg: foreignImagesBakes[27],
        price: 98000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.green]: imagesBakes[26],
            [EnumOfColors.black]: imagesBakes[27],
        },
        searchString: 'eone sixty merida двухподвесной черный',
        description: 'Велосипед, созданный для жесткой эксплуатации в горах. Руль шириной 800 мм станет идеальным инструментом контроля на спусках. Производитель позаботился о сохранности рамы, оснастил заднее перо заводской защитой от ударов цепи, которая органично смотрится и не выглядит чужеродным элементом. Подвеска Maestro гасит удары и рассчитана на повышенные нагрузки, в том числе благодаря пружинному амортизатору.',
    },

    {
        uuid: '111',
        id: '34111',
        name: 'Scott Strike Eride',
        img: imagesBakes[28],
        foreignImg: foreignImagesBakes[28],
        price: 115000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[28],
            [EnumOfColors.black]: imagesBakes[29],
        },
        searchString: 'scott strike eride bulls двухподвесной оранжевый',
        description: 'Спортивная модель, которая способна одинаково хорошо передвигаться и по хорошим дорогам, и по просёлочным. Модель укомплектована любительским уровнем оборудования. У велосипеда дисковые гидравлические тормоза MT201, которые срабатывают всегда точно и эффективно.',
    },
    {
        uuid: '111',
        id: '88111',
        name: 'Scott Strike Eride',
        img: imagesBakes[29],
        foreignImg: foreignImagesBakes[29],
        price: 115000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.orange],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[28],
            [EnumOfColors.black]: imagesBakes[29],
        },
        searchString: 'scott strike eride bulls двухподвесной черный',
        description: 'Спортивная модель, которая способна одинаково хорошо передвигаться и по хорошим дорогам, и по просёлочным. Модель укомплектована любительским уровнем оборудования. У велосипеда дисковые гидравлические тормоза MT201, которые срабатывают всегда точно и эффективно.',
    },

    {
        uuid: '112',
        id: '87112',
        name: 'Cube Stereo Hybrid',
        img: imagesBakes[30],
        foreignImg: foreignImagesBakes[30],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[30],
            [EnumOfColors.black]: imagesBakes[31],
        },
        searchString: 'cube stereo hybrid trek двухподвесной оранжевый',
        description: 'Модель, сочетающая продуманную сбалансированную раму и надежное навесное оборудование. Переключатель помогает комфортно и вовремя переключать скорости. Модель обладает прочными покрышками с глубоким протектором. В комплектацию включены дисковые гидравлические тормоза. Вилка нейтрализует различные неровности дороги. Усиленная рама гарантирует оптимальное распределение веса тела.',
    },
    {
        uuid: '112',
        id: '34112',
        name: 'Cube Stereo Hybrid',
        img: imagesBakes[31],
        foreignImg: foreignImagesBakes[31],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.doubleSuspended,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.orange],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[30],
            [EnumOfColors.black]: imagesBakes[31],
        },
        searchString: 'cube stereo hybrid trek двухподвесной черный',
        description: 'Модель, сочетающая продуманную сбалансированную раму и надежное навесное оборудование. Переключатель помогает комфортно и вовремя переключать скорости. Модель обладает прочными покрышками с глубоким протектором. В комплектацию включены дисковые гидравлические тормоза. Вилка нейтрализует различные неровности дороги. Усиленная рама гарантирует оптимальное распределение веса тела.',
    },


    // electrical
    {
        uuid: '113',
        id: '86113',
        name: 'Eltreco XT',
        img: imagesBakes[32],
        foreignImg: foreignImagesBakes[32],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[32],
            [EnumOfColors.blue]: imagesBakes[33],
            [EnumOfColors.grey]: imagesBakes[34],
            [EnumOfColors.red]: imagesBakes[35],
            [EnumOfColors.green]: imagesBakes[36],
            [EnumOfColors.black]: imagesBakes[37],
        },
        searchString: 'eltreco xt trek электро оранжевый',
        description: 'Топовая модель с двигателем 500W, что обеспечит мгновенный разгон и скорость составляет 38 километров. Увеличенная емкость аккумулятора 10Ah, которого хватает на 50 км. Колеса размером 27.5 дюйма проедут где угодно и за счет диаметра меньше ощущаются кочки. Установленные гидравлические дисковые тормоза, которые справляются с высокими скоростями и погодными условиями.',
    },
    {
        uuid: '113',
        id: '44113',
        name: 'Eltreco XT',
        img: imagesBakes[33],
        foreignImg: foreignImagesBakes[33],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.orange, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[32],
            [EnumOfColors.blue]: imagesBakes[33],
            [EnumOfColors.grey]: imagesBakes[34],
            [EnumOfColors.red]: imagesBakes[35],
            [EnumOfColors.green]: imagesBakes[36],
            [EnumOfColors.black]: imagesBakes[37],
        },
        searchString: 'eltreco xt trek электро синий',
        description: 'Топовая модель с двигателем 500W, что обеспечит мгновенный разгон и скорость составляет 38 километров. Увеличенная емкость аккумулятора 10Ah, которого хватает на 50 км. Колеса размером 27.5 дюйма проедут где угодно и за счет диаметра меньше ощущаются кочки. Установленные гидравлические дисковые тормоза, которые справляются с высокими скоростями и погодными условиями.',
    },
    {
        uuid: '113',
        id: '54113',
        name: 'Eltreco XT',
        img: imagesBakes[34],
        foreignImg: foreignImagesBakes[34],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.orange, EnumOfColors.blue, EnumOfColors.red, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[32],
            [EnumOfColors.blue]: imagesBakes[33],
            [EnumOfColors.grey]: imagesBakes[34],
            [EnumOfColors.red]: imagesBakes[35],
            [EnumOfColors.green]: imagesBakes[36],
            [EnumOfColors.black]: imagesBakes[37],
        },
        searchString: 'eltreco xt trek электро серый',
        description: 'Топовая модель с двигателем 500W, что обеспечит мгновенный разгон и скорость составляет 38 километров. Увеличенная емкость аккумулятора 10Ah, которого хватает на 50 км. Колеса размером 27.5 дюйма проедут где угодно и за счет диаметра меньше ощущаются кочки. Установленные гидравлические дисковые тормоза, которые справляются с высокими скоростями и погодными условиями.',
    },
    {
        uuid: '113',
        id: '15113',
        name: 'Eltreco XT',
        img: imagesBakes[35],
        foreignImg: foreignImagesBakes[35],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[32],
            [EnumOfColors.blue]: imagesBakes[33],
            [EnumOfColors.grey]: imagesBakes[34],
            [EnumOfColors.red]: imagesBakes[35],
            [EnumOfColors.green]: imagesBakes[36],
            [EnumOfColors.black]: imagesBakes[37],
        },
        searchString: 'eltreco xt trek электро красный',
        description: 'Топовая модель с двигателем 500W, что обеспечит мгновенный разгон и скорость составляет 38 километров. Увеличенная емкость аккумулятора 10Ah, которого хватает на 50 км. Колеса размером 27.5 дюйма проедут где угодно и за счет диаметра меньше ощущаются кочки. Установленные гидравлические дисковые тормоза, которые справляются с высокими скоростями и погодными условиями.',
    },
    {
        uuid: '113',
        id: '25113',
        name: 'Eltreco XT',
        img: imagesBakes[36],
        foreignImg: foreignImagesBakes[36],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.orange, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[32],
            [EnumOfColors.blue]: imagesBakes[33],
            [EnumOfColors.grey]: imagesBakes[34],
            [EnumOfColors.red]: imagesBakes[35],
            [EnumOfColors.green]: imagesBakes[36],
            [EnumOfColors.black]: imagesBakes[37],
        },
        searchString: 'eltreco xt trek электро зелёный',
        description: 'Топовая модель с двигателем 500W, что обеспечит мгновенный разгон и скорость составляет 38 километров. Увеличенная емкость аккумулятора 10Ah, которого хватает на 50 км. Колеса размером 27.5 дюйма проедут где угодно и за счет диаметра меньше ощущаются кочки. Установленные гидравлические дисковые тормоза, которые справляются с высокими скоростями и погодными условиями.',
    },
    {
        uuid: '113',
        id: '35113',
        name: 'Eltreco XT',
        img: imagesBakes[37],
        foreignImg: foreignImagesBakes[37],
        price: 120000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.orange, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[32],
            [EnumOfColors.blue]: imagesBakes[33],
            [EnumOfColors.grey]: imagesBakes[34],
            [EnumOfColors.red]: imagesBakes[35],
            [EnumOfColors.green]: imagesBakes[36],
            [EnumOfColors.black]: imagesBakes[37],
        },
        searchString: 'eltreco xt trek электро черный',
        description: 'Топовая модель с двигателем 500W, что обеспечит мгновенный разгон и скорость составляет 38 километров. Увеличенная емкость аккумулятора 10Ah, которого хватает на 50 км. Колеса размером 27.5 дюйма проедут где угодно и за счет диаметра меньше ощущаются кочки. Установленные гидравлические дисковые тормоза, которые справляются с высокими скоростями и погодными условиями.',
    },

    {
        uuid: '114',
        id: '45114',
        name: 'Eltreco FS',
        img: imagesBakes[38],
        foreignImg: foreignImagesBakes[38],
        price: 135000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.grey, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[38],
            [EnumOfColors.grey]: imagesBakes[39],
            [EnumOfColors.black]: imagesBakes[40],
        },
        searchString: 'eltreco fs bulls электро оранжевый',
        description: 'Старшая модель Alfa особенностью, которой является аккумулятор на 12.5 Ah, что делает возможным проехать около 60 км. Задняя платформа делает возможным перевозить как грузы, так и пассажира за счет раскладывания нижней опоры. Аккумулятор легко вытаскивается и упрощает зарядку.',
    },
    {
        uuid: '114',
        id: '85114',
        name: 'Eltreco FS',
        img: imagesBakes[39],
        foreignImg: foreignImagesBakes[39],
        price: 135000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.orange, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[38],
            [EnumOfColors.grey]: imagesBakes[39],
            [EnumOfColors.black]: imagesBakes[40],
        },
        searchString: 'eltreco fs bulls электро серый',
        description: 'Старшая модель Alfa особенностью, которой является аккумулятор на 12.5 Ah, что делает возможным проехать около 60 км. Задняя платформа делает возможным перевозить как грузы, так и пассажира за счет раскладывания нижней опоры. Аккумулятор легко вытаскивается и упрощает зарядку.',
    },
    {
        uuid: '114',
        id: '55114',
        name: 'Eltreco FS',
        img: imagesBakes[40],
        foreignImg: foreignImagesBakes[40],
        price: 135000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.orange, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[38],
            [EnumOfColors.grey]: imagesBakes[39],
            [EnumOfColors.black]: imagesBakes[40],
        },
        searchString: 'eltreco fs bulls электро черный',
        description: 'Старшая модель Alfa особенностью, которой является аккумулятор на 12.5 Ah, что делает возможным проехать около 60 км. Задняя платформа делает возможным перевозить как грузы, так и пассажира за счет раскладывания нижней опоры. Аккумулятор легко вытаскивается и упрощает зарядку.',
    },

    {
        uuid: '115',
        id: '84115',
        name: 'Cube Stereo Hybrid',
        img: imagesBakes[41],
        foreignImg: foreignImagesBakes[41],
        price: 200000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[41],
            [EnumOfColors.green]: imagesBakes[42],
            [EnumOfColors.black]: imagesBakes[43],
        },
        searchString: 'cube stereo hybrid merida электро синий',
        description: 'Электровелосипед заточен под агрессивный стиль катания. Предназначен для катания по бездорожью или лесным тропикам, поездка будет настолько же комфортной как в городе или по тропинкам в парке. Электропривод 250Вт и аккумулятор на 400 Вт/ч обеспечивают пробег более 100 км. Воздушно-масляная подвеска настраивается под любой вес райдера.',
    },
    {
        uuid: '115',
        id: '16115',
        name: 'Cube Stereo Hybrid',
        img: imagesBakes[42],
        foreignImg: foreignImagesBakes[42],
        price: 200000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.blue, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[41],
            [EnumOfColors.green]: imagesBakes[42],
            [EnumOfColors.black]: imagesBakes[43],
        },
        searchString: 'cube stereo hybrid merida электро зелёный',
        description: 'Электровелосипед заточен под агрессивный стиль катания. Предназначен для катания по бездорожью или лесным тропикам, поездка будет настолько же комфортной как в городе или по тропинкам в парке. Электропривод 250Вт и аккумулятор на 400 Вт/ч обеспечивают пробег более 100 км. Воздушно-масляная подвеска настраивается под любой вес райдера.',
    },
    {
        uuid: '115',
        id: '26115',
        name: 'Cube Stereo Hybrid',
        img: imagesBakes[43],
        foreignImg: foreignImagesBakes[43],
        price: 200000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.green, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[41],
            [EnumOfColors.green]: imagesBakes[42],
            [EnumOfColors.black]: imagesBakes[43],
        },
        searchString: 'cube stereo hybrid merida электро черный',
        description: 'Электровелосипед заточен под агрессивный стиль катания. Предназначен для катания по бездорожью или лесным тропикам, поездка будет настолько же комфортной как в городе или по тропинкам в парке. Электропривод 250Вт и аккумулятор на 400 Вт/ч обеспечивают пробег более 100 км. Воздушно-масляная подвеска настраивается под любой вес райдера.',
    },

    {
        uuid: '116',
        id: '36116',
        name: 'Reaction Hybrid',
        img: imagesBakes[44],
        foreignImg: foreignImagesBakes[44],
        price: 180000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.grey]: imagesBakes[44],
            [EnumOfColors.red]: imagesBakes[45],
        },
        searchString: 'reaction hybrid stinger электро серый',
        description: 'Прочная модель для любителей активного отдыха. Велосипед имеет дисковые гидравлические тормоза для эффективного и быстрого торможения. Цепная передача оснащена износоустойчивыми шатунами. Прочная и лёгкая алюминиевая рама. К достоинствам модели относится удачное сочетание превосходных ходовых качеств и полупрофессионального навесного оборудования.',
    },
    {
        uuid: '116',
        id: '83116',
        name: 'Reaction Hybrid',
        img: imagesBakes[45],
        foreignImg: foreignImagesBakes[45],
        price: 180000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.electrical,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.grey],
        imgsByColor: {
            [EnumOfColors.grey]: imagesBakes[44],
            [EnumOfColors.red]: imagesBakes[45],
        },
        searchString: 'reaction hybrid stinger электро красный',
        description: 'Прочная модель для любителей активного отдыха. Велосипед имеет дисковые гидравлические тормоза для эффективного и быстрого торможения. Цепная передача оснащена износоустойчивыми шатунами. Прочная и лёгкая алюминиевая рама. К достоинствам модели относится удачное сочетание превосходных ходовых качеств и полупрофессионального навесного оборудования.',
    },


    //детские
    {
        uuid: '117',
        id: '01117',
        name: 'Globber',
        img: imagesBakes[46],
        foreignImg: foreignImagesBakes[46],
        price: 10000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.kids,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.red, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[46],
            [EnumOfColors.red]: imagesBakes[47],
            [EnumOfColors.black]: imagesBakes[48],
        },
        searchString: 'globber bulls детский синий',
        description: 'Стильная и надёжная детская модель, которая позволит самым маленьким наслаждаться увлекательными велосипедными поездками. Велосипед оснащён жёсткой вилкой. Рама изготавливается из стали. Колёса с жесткими покрышками в свою очередь сохраняют устойчивость и делают преодоление преград легким.',
    },
    {
        uuid: '117',
        id: '02117',
        name: 'Globber',
        img: imagesBakes[47],
        foreignImg: foreignImagesBakes[47],
        price: 10000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.kids,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.blue, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[46],
            [EnumOfColors.red]: imagesBakes[47],
            [EnumOfColors.black]: imagesBakes[48],
        },
        searchString: 'globber bulls детский красный',
        description: 'Стильная и надёжная детская модель, которая позволит самым маленьким наслаждаться увлекательными велосипедными поездками. Велосипед оснащён жёсткой вилкой. Рама изготавливается из стали. Колёса с жесткими покрышками в свою очередь сохраняют устойчивость и делают преодоление преград легким.',
    },
    {
        uuid: '117',
        id: '03117',
        name: 'Globber',
        img: imagesBakes[48],
        foreignImg: foreignImagesBakes[48],
        price: 10000,
        company: EnumOfCompanies.bulls,
        type: EnumOfTypes.kids,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.blue, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[46],
            [EnumOfColors.red]: imagesBakes[47],
            [EnumOfColors.black]: imagesBakes[48],
        },
        searchString: 'globber bulls детский черный',
        description: 'Стильная и надёжная детская модель, которая позволит самым маленьким наслаждаться увлекательными велосипедными поездками. Велосипед оснащён жёсткой вилкой. Рама изготавливается из стали. Колёса с жесткими покрышками в свою очередь сохраняют устойчивость и делают преодоление преград легким.',
    },

    {
        uuid: '118',
        id: '82118',
        name: 'Novatrack Titanium',
        img: imagesBakes[50],
        foreignImg: foreignImagesBakes[50],
        price: 15000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.kids,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.red]: imagesBakes[50],
            [EnumOfColors.green]: imagesBakes[49],
        },
        searchString: 'novatrack titanium stinger детский красный',
        description: 'Детский велосипед настоящая находка для ребёнка от 5 до 9 лет. Навесное оборудование также включает в себя шатуны. Колёса оснащены фирменными покрышками, удобными для катания по городскому асфальту и дачным тропам. Мощная алюминиевая рама отлично выдерживает нагрузки при активном катании. Удобное седло с противоскользящей поверхностью. Жёсткая вилка даёт максимальный контроль над велосипедом.',
    },
    {
        uuid: '118',
        id: '46118',
        name: 'Novatrack Titanium',
        img: imagesBakes[49],
        foreignImg: foreignImagesBakes[49],
        price: 15000,
        company: EnumOfCompanies.stinger,
        type: EnumOfTypes.kids,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.red]: imagesBakes[50],
            [EnumOfColors.green]: imagesBakes[49],
        },
        searchString: 'gnovatrack titanium stinger детский зелёный',
        description: 'Детский велосипед настоящая находка для ребёнка от 5 до 9 лет. Навесное оборудование также включает в себя шатуны. Колёса оснащены фирменными покрышками, удобными для катания по городскому асфальту и дачным тропам. Мощная алюминиевая рама отлично выдерживает нагрузки при активном катании. Удобное седло с противоскользящей поверхностью. Жёсткая вилка даёт максимальный контроль над велосипедом.',
    },

    {
        uuid: '119',
        id: '81119',
        name: 'Wahoo',
        img: imagesBakes[51],
        foreignImg: foreignImagesBakes[51],
        price: 18000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.kids,
        color: EnumOfColors.blue,
        mayBeColors: [EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[51],
            [EnumOfColors.grey]: imagesBakes[52],
            [EnumOfColors.red]: imagesBakes[53],
            [EnumOfColors.black]: imagesBakes[54],

        },
        searchString: 'wahoo trek детский синий',
        description: 'Модель для малышей, предпочитающих весёлые активные игры. Велосипед оборудован седлом комфортной геометрии. Прочные и долговечные покрышки. Несомненный плюс модели — алюминиевая рама, качественно обеспечивающая равновесие, безопасность и динамичность езды. Есть переключатель передач высокой чёткости. Дисковые механические тормоза, приспособлены сделать езду безопасной в любой ситуации.',
    },
    {
        uuid: '119',
        id: '56119',
        name: 'Wahoo',
        img: imagesBakes[52],
        foreignImg: foreignImagesBakes[52],
        price: 18000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.kids,
        color: EnumOfColors.grey,
        mayBeColors: [EnumOfColors.grey, EnumOfColors.blue, EnumOfColors.red, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[51],
            [EnumOfColors.grey]: imagesBakes[52],
            [EnumOfColors.red]: imagesBakes[53],
            [EnumOfColors.black]: imagesBakes[54],

        },
        searchString: 'wahoo trek детский серый',
        description: 'Модель для малышей, предпочитающих весёлые активные игры. Велосипед оборудован седлом комфортной геометрии. Прочные и долговечные покрышки. Несомненный плюс модели — алюминиевая рама, качественно обеспечивающая равновесие, безопасность и динамичность езды. Есть переключатель передач высокой чёткости. Дисковые механические тормоза, приспособлены сделать езду безопасной в любой ситуации.',
    },
    {
        uuid: '119',
        id: '17119',
        name: 'Wahoo',
        img: imagesBakes[53],
        foreignImg: foreignImagesBakes[53],
        price: 18000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.kids,
        color: EnumOfColors.red,
        mayBeColors: [EnumOfColors.red, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.black],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[51],
            [EnumOfColors.grey]: imagesBakes[52],
            [EnumOfColors.red]: imagesBakes[53],
            [EnumOfColors.black]: imagesBakes[54],

        },
        searchString: 'wahoo trek детский красный',
        description: 'Модель для малышей, предпочитающих весёлые активные игры. Велосипед оборудован седлом комфортной геометрии. Прочные и долговечные покрышки. Несомненный плюс модели — алюминиевая рама, качественно обеспечивающая равновесие, безопасность и динамичность езды. Есть переключатель передач высокой чёткости. Дисковые механические тормоза, приспособлены сделать езду безопасной в любой ситуации.',
    },
    {
        uuid: '119',
        id: '80119',
        name: 'Wahoo',
        img: imagesBakes[54],
        foreignImg: foreignImagesBakes[54],
        price: 18000,
        company: EnumOfCompanies.trek,
        type: EnumOfTypes.kids,
        color: EnumOfColors.black,
        mayBeColors: [EnumOfColors.black, EnumOfColors.blue, EnumOfColors.grey, EnumOfColors.red],
        imgsByColor: {
            [EnumOfColors.blue]: imagesBakes[51],
            [EnumOfColors.grey]: imagesBakes[52],
            [EnumOfColors.red]: imagesBakes[53],
            [EnumOfColors.black]: imagesBakes[54],

        },
        searchString: 'wahoo trek детский серый черный',
        description: 'Модель для малышей, предпочитающих весёлые активные игры. Велосипед оборудован седлом комфортной геометрии. Прочные и долговечные покрышки. Несомненный плюс модели — алюминиевая рама, качественно обеспечивающая равновесие, безопасность и динамичность езды. Есть переключатель передач высокой чёткости. Дисковые механические тормоза, приспособлены сделать езду безопасной в любой ситуации.',
    },

    {
        uuid: '120',
        id: '27120',
        name: 'Giant',
        img: imagesBakes[55],
        foreignImg: foreignImagesBakes[55],
        price: 16000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.kids,
        color: EnumOfColors.orange,
        mayBeColors: [EnumOfColors.orange, EnumOfColors.green],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[55],
            [EnumOfColors.green]: imagesBakes[56],
        },
        searchString: 'giant merida детский оранжевый',
        description: 'Модель для детей от 115 до 130см. Модель оснащена фирменными покрышками 20x2.0. Для быстрых остановок используются отлично себя проявляющие ободные механические тормоза V-типа. Велосипед оснащён шатунами. Изменить скоростной режим можно при помощи переключателя. Алюминиевая рама отличается лёгкостью и высокой прочностью. Жёсткая вилка даёт максимальный контроль над велосипедом.',
    },
    {
        uuid: '120',
        id: '79120',
        name: 'Giant',
        img: imagesBakes[56],
        foreignImg: foreignImagesBakes[56],
        price: 16000,
        company: EnumOfCompanies.merida,
        type: EnumOfTypes.kids,
        color: EnumOfColors.green,
        mayBeColors: [EnumOfColors.green, EnumOfColors.orange],
        imgsByColor: {
            [EnumOfColors.orange]: imagesBakes[55],
            [EnumOfColors.green]: imagesBakes[56],
        },
        searchString: 'giant merida детский зелёный',
        description: 'Модель для детей от 115 до 130см. Модель оснащена фирменными покрышками 20x2.0. Для быстрых остановок используются отлично себя проявляющие ободные механические тормоза V-типа. Велосипед оснащён шатунами. Изменить скоростной режим можно при помощи переключателя. Алюминиевая рама отличается лёгкостью и высокой прочностью. Жёсткая вилка даёт максимальный контроль над велосипедом.',
    },
];

const recommendation = {
    [EnumOfTypes.mountain]: [b1[3], b1[6], b1[9], b1[11], b1[0], b1[16], b1[1], b1[13]],
    [EnumOfTypes.doubleSuspended]: [b1[17], b1[20], b1[23], b1[27], b1[29], b1[30], b1[25], b1[18]],
    [EnumOfTypes.electrical]: [b1[33], b1[39], b1[41], b1[44], b1[34], b1[43], b1[36], b1[35]],
    [EnumOfTypes.kids]: [b1[56], b1[49], b1[51], b1[54], b1[46], b1[50], b1[52], b1[55]],
};

const bikes = b1.sort((a, b) => a.id > b.id ? -1 : 1);

export { bikes, recommendation };